name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # ВОТ ЭТО РЕШАЕТ ОШИБКУ 403

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install OpenMP (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install libomp-dev

      - name: Compile (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: g++ -O3 main.cpp -o Mandelbrot_linux -fopenmp -static-libstdc++ -static-libgcc

      - name: Compile (Windows)
        if: matrix.os == 'windows-latest'
        run: g++ -O3 main.cpp -o Mandelbrot_windows.exe -fopenmp -static

      - name: Upload Artifacts # Сначала сохраним файлы в облако
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}
          path: |
            Mandelbrot_linux
            Mandelbrot_windows.exe

  release: # Отдельный шаг для создания релиза, когда ОБЕ сборки готовы
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            binary-ubuntu-latest/Mandelbrot_linux
            binary-windows-latest/Mandelbrot_windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

