name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install OpenMP (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install libomp-dev
      - name: Compile (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          g++ -O3 main.cpp -o Mandelbrot_linux -fopenmp -static-libstdc++ -static-libgcc
          strip Mandelbrot_linux
      - name: Compile (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          windres resource.rc -o resource.o
          g++ -O3 main.cpp resource.o -o Mandelbrot_windows.exe -fopenmp -static
          strip Mandelbrot_windows.exe
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}
          path: |
            Mandelbrot_linux
            Mandelbrot_windows.exe
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Mandelbrot set. 24-bit TrueColor. 80-bit long double. OpenMP. Supersampling 8x8 (64 passes). Colors ${{ github.ref_name }}"
          body: |
            ## Mandelbrot set. 24-bit TrueColor. 80-bit long double. OpenMP. Supersampling 8x8 (64 passes). Colors
            <img src="https://github.com/${{ github.repository }}/raw/main/Mandelbrot1.png" width="800">
            <img src="https://github.com/${{ github.repository }}/raw/main/Mandelbrot2.png" width="800">
            <img src="https://github.com/${{ github.repository }}/raw/main/Mandelbrot3.png" width="800">
            <img src="https://github.com/${{ github.repository }}/raw/main/Mandelbrot4.png" width="800">
            <img src="https://github.com/${{ github.repository }}/raw/main/Mandelbrot5.png" width="800">

            ### Features:
            * True 24-bit BGR TrueColor
            * High-Precision Rendering (80-bit)
            * Multi-threaded performance (OpenMP)
            * True SSAA 8x8 (64 independent samples per pixel) direct RGB-space integration
            * Harmonic oscillations (G, B) with per-index noise (R), a unique shimmering texture
          files: |
            binary-ubuntu-latest/Mandelbrot_linux
            binary-windows-latest/Mandelbrot_windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PAT }}
